function sigmoid(x){return 1/(1+Math.exp(-Math.max(-20,Math.min(20,x))));}

if (document.querySelector('#game')) {
const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const scoreEl = document.querySelector('#score');
const bestEl = document.querySelector('#best-score');
const overlay = document.querySelector('#game-overlay');
const overlayTitle = document.querySelector('#overlay-title');
const overlayText = document.querySelector('#overlay-text');
const overlayButton = document.querySelector('#overlay-button');
let best = Number(localStorage.getItem('flappyLearnsBest') || 0);
let running = false, animation, score = 0, bird, pipes, frame;
bestEl.textContent = best;

function reset() { bird = { x:95, y:250, radius:16, velocity:0, rotation:0 }; pipes=[]; frame=0; score=0; scoreEl.textContent=0; }
function start() { reset(); running=true; overlay.classList.add('hidden'); cancelAnimationFrame(animation); loop(); canvas.focus(); }
function flap() { if (!running) start(); else bird.velocity=-7.2; }
function end() { running=false; overlayTitle.textContent='Splat!'; overlayText.innerHTML=`You scored <b>${score}</b>. Press SPACE for another try.`; overlayButton.textContent='Fly again'; overlay.classList.remove('hidden'); if(score>best) { best=score; localStorage.setItem('flappyLearnsBest',best); bestEl.textContent=best; } }
function addPipe() { const gap=142; const top=75+Math.random()*190; pipes.push({x:canvas.width+25, top, bottom:top+gap, passed:false}); }
function drawCloud(x,y,s) { ctx.fillStyle='rgba(255,255,255,.76)'; ctx.beginPath(); ctx.arc(x,y,16*s,0,Math.PI*2);ctx.arc(x+20*s,y-9*s,21*s,0,Math.PI*2);ctx.arc(x+44*s,y,15*s,0,Math.PI*2);ctx.fill(); }
function drawPipe(p) { ctx.fillStyle='#63b945'; ctx.strokeStyle='#245e39'; ctx.lineWidth=3; ctx.fillRect(p.x,0,55,p.top);ctx.strokeRect(p.x,0,55,p.top);ctx.fillRect(p.x-5,p.top-22,65,22);ctx.strokeRect(p.x-5,p.top-22,65,22);ctx.fillRect(p.x,p.bottom,55,canvas.height-p.bottom-44);ctx.strokeRect(p.x,p.bottom,55,canvas.height-p.bottom-44);ctx.fillRect(p.x-5,p.bottom,65,22);ctx.strokeRect(p.x-5,p.bottom,65,22); }
function drawBird() { const b=bird; ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.max(-.35,Math.min(.7,b.velocity*.07))); ctx.fillStyle='#ffd842';ctx.strokeStyle='#17354a';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,b.radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#f39c38';ctx.beginPath();ctx.ellipse(-9,6,11,6,-.35,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(7,-7,6,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#17354a';ctx.beginPath();ctx.arc(9,-7,2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ef7544';ctx.beginPath();ctx.moveTo(14,2);ctx.lineTo(28,7);ctx.lineTo(14,11);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore(); }
function loop() { ctx.fillStyle='#80d8ef';ctx.fillRect(0,0,canvas.width,canvas.height);drawCloud(45,95,.8);drawCloud(285,150,.55);ctx.fillStyle='#87cf5c';ctx.fillRect(0,canvas.height-44,canvas.width,44);ctx.fillStyle='#d6a85d';ctx.fillRect(0,canvas.height-28,canvas.width,28); if(frame%96===0) addPipe(); pipes.forEach(p=>{p.x-=2.55;drawPipe(p)});pipes=pipes.filter(p=>p.x>-70);bird.velocity+=.42;bird.y+=bird.velocity;drawBird();for(const p of pipes){if(!p.passed&&p.x+55<bird.x){p.passed=true;score++;scoreEl.textContent=score;}if(bird.x+bird.radius>p.x&&bird.x-bird.radius<p.x+55&&(bird.y-bird.radius<p.top||bird.y+bird.radius>p.bottom)){end();return;}}if(bird.y+bird.radius>=canvas.height-44||bird.y-bird.radius<0){end();return;}frame++;animation=requestAnimationFrame(loop); }
function gameAction(e) { if(e.type==='keydown' && e.code!=='Space') return; if(e.type==='keydown') e.preventDefault(); flap(); }
document.addEventListener('keydown',gameAction);canvas.addEventListener('pointerdown',gameAction);overlayButton.addEventListener('click',start);document.querySelector('#start-button').addEventListener('click',()=>{document.querySelector('.game-shell').scrollIntoView({behavior:'smooth',block:'center'});setTimeout(start,350)});reset();ctx.fillStyle='#80d8ef';ctx.fillRect(0,0,canvas.width,canvas.height);drawCloud(45,95,.8);drawCloud(285,150,.55);ctx.fillStyle='#87cf5c';ctx.fillRect(0,516,420,44);drawBird();
}

if (document.querySelector('.lesson-section')) {
const tabs=[...document.querySelectorAll('.deck-tab')],decks=[...document.querySelectorAll('.deck')],dialog=document.querySelector('#learn-more-dialog'),detailTitle=document.querySelector('#detail-title'),detailContent=document.querySelector('#detail-content'),closeDetail=document.querySelector('.detail-close');let activeDeck='basics',activeSlide=0,lastDetailTrigger;
const details={
 'basics-1':['Why this game works','Flappy Bird is a useful learning world because the rules are simple but the timing is not. Gravity changes the bird’s height every frame, while pipes create a moving target. A successful player must repeatedly predict where the bird will be when it reaches the gap.'],
 'basics-2':['A decision every frame','The only action is flap, but doing nothing is also a decision. A flap changes vertical velocity, not the bird’s position instantly. That delay means a good controller learns to act a little before the bird reaches the height it wants.'],
 'basics-3':['A measurable goal','The score turns “play well” into a number. In machine learning this is a reward signal: it lets us compare two attempts. The score does not explain how to improve, so the training method has to discover useful choices from many tries.'],
 'basics-4':['Same world, new controller','Nothing about gravity, pipes, or scoring changes when the network takes over. This is important: the network is judged against exactly the same challenge as a human player. Its inputs replace what our eyes notice; its output replaces a key press.'],
 'network-1':['Turning a scene into numbers','Neural networks cannot see a pipe unless we describe it numerically. Height and velocity describe the bird; distance and the two gap edges describe the next obstacle. Scaling these values to similar ranges helps the network treat each clue fairly.'],
 'network-2':['Layers build combinations','Each neuron combines the values it receives and passes on a transformed result. Early hidden neurons can respond to patterns such as “below the gap and falling.” Later neurons combine those patterns into one flap-or-wait decision.'],
 'network-3':['What a weight means','A weight says how strongly one signal should affect the next neuron. A positive weight makes a larger input push upward; a negative one pushes downward. Bias is a starting offset, so a neuron can prefer an action even when its inputs are quiet.'],
 'network-4':['From confidence to action','The output is a number between 0 and 1 after an activation function squeezes it into that range. This project uses 0.5 as the decision boundary: above it, flap; at or below it, wait. Changing weights moves that boundary.'],
 'evolution-1':['Variation comes first','At the start, random weights produce random-looking behavior. That is not a mistake: evolution needs different candidates to compare. A few birds may accidentally flap at helpful moments, giving selection something promising to preserve.'],
 'evolution-2':['Fitness ranks attempts','Fitness is the rule for deciding which birds did better. Distance, pipes passed, and survival time are useful because they reward the behavior we care about. A clear fitness score lets an evolutionary algorithm rank an entire population without being told the right move at each frame.'],
 'evolution-3':['Selection keeps discoveries','Keeping only the best performers is called selection. It concentrates the next generation around successful ideas, but keeping several parents matters too: different birds may have found different useful strategies, and diversity makes the population less fragile.'],
 'evolution-4':['Mutation explores nearby ideas','Children copy a parent’s network, then mutation nudges some weights. Most nudges will not help, but occasional ones reveal a better timing rule. Repeating copy, test, select, and mutate turns lucky improvements into a gradual search.'],
 'strategy-1':['Elitism protects progress','The best three are copied unchanged into the next generation. This is called elitism. It prevents a strong network from disappearing only because all of its children happened to mutate in unhelpful ways.'],
 'strategy-2':['A fair test is essential','If every bird sees a different random course, one may win because it got an easier path. Reusing the same early courses makes scores comparable. It is the same reason scientists try to hold conditions steady when comparing experiments.'],
 'strategy-3':['Training beyond easy examples','A bird that only survives wide, slow gaps has not learned much. Increasing speed and narrowing gaps gradually is curriculum learning: start with a challenge that gives useful feedback, then demand more as the population improves.'],
 'strategy-4':['Explore versus refine','Small mutations carefully improve a working behavior, while large mutations jump to unfamiliar possibilities. Too little exploration can trap a population in a merely okay strategy; too much can erase good behavior. The mutation control lets you see that trade-off.']
};
function closeDetails(){if(dialog.open)dialog.close();}
function renderSlides(){const deck=document.querySelector(`#deck-${activeDeck}`),slides=[...deck.querySelectorAll('.slide')];slides.forEach((slide,i)=>slide.classList.toggle('active',i===activeSlide));document.querySelector('#slide-status').textContent=`Slide ${activeSlide+1} of ${slides.length}`;document.querySelector('#previous-slide').disabled=activeSlide===0;document.querySelector('#next-slide').disabled=activeSlide===slides.length-1;}
tabs.forEach(tab=>tab.addEventListener('click',()=>{closeDetails();activeDeck=tab.dataset.deck;activeSlide=0;tabs.forEach(t=>{const on=t===tab;t.classList.toggle('active',on);t.setAttribute('aria-selected',on)});decks.forEach(d=>{const on=d.id===`deck-${activeDeck}`;d.classList.toggle('active',on);d.hidden=!on});renderSlides();}));
document.querySelector('#previous-slide').addEventListener('click',()=>{closeDetails();activeSlide--;renderSlides()});document.querySelector('#next-slide').addEventListener('click',()=>{closeDetails();activeSlide++;renderSlides()});
document.querySelectorAll('.learn-more').forEach(button=>{button.setAttribute('aria-controls','learn-more-dialog');button.setAttribute('aria-expanded','false');button.addEventListener('click',()=>{lastDetailTrigger=button;const [title,content]=details[button.closest('.slide').dataset.detail];detailTitle.textContent=title;detailContent.textContent=content;button.setAttribute('aria-expanded','true');dialog.showModal();});});
closeDetail.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});dialog.addEventListener('close',()=>{lastDetailTrigger?.setAttribute('aria-expanded','false');lastDetailTrigger?.focus();});renderSlides();
}

// Manual-training lab: a deliberately small 5 input -> 1 output neural network (a perceptron).
if (document.querySelector('#bot-game')) {
const botCanvas=document.querySelector('#bot-game'), botCtx=botCanvas.getContext('2d');
const botScoreEl=document.querySelector('#bot-score'), botBestEl=document.querySelector('#bot-best'), botOutputEl=document.querySelector('#bot-output'), botActionEl=document.querySelector('#bot-action');
const inputNames=['Bird height','Vertical speed','Pipe distance','Gap top','Gap bottom'];
let brain, bot, botPipes, botFrame=0, botScore=0, botBest=Number(localStorage.getItem('manualBirdBest')||0), botRunning=false, botAnimation;
botBestEl.textContent=botBest;
const starter=()=>({w:[5,1.2,0,-2.5,-2.5],b:0});
function randomBrain(){return {w:Array.from({length:5},()=>+(Math.random()*8-4).toFixed(2)),b:+(Math.random()*4-2).toFixed(2)};}
brain=starter();
function addControl(parent,label,get,set){const row=document.createElement('label');row.className='weight-row';const name=document.createElement('span');name.textContent=label;const slider=document.createElement('input');slider.type='range';slider.min='-6';slider.max='6';slider.step='.1';slider.value=get();const value=document.createElement('output');value.className='weight-value';value.textContent=Number(get()).toFixed(1);slider.addEventListener('input',()=>{set(Number(slider.value));value.textContent=Number(slider.value).toFixed(1);drawActivations(think());});row.append(name,slider,value);parent.append(row);}
function renderControls(){const root=document.querySelector('#nn-controls');root.replaceChildren();const weights=document.createElement('section');weights.className='weight-section';weights.innerHTML='<h4>Five inputs <span>→</span> flap output</h4>';inputNames.forEach((input,i)=>addControl(weights,`${input} → flap`,()=>brain.w[i],v=>brain.w[i]=v));root.append(weights);const bias=document.createElement('section');bias.className='weight-section';bias.innerHTML='<h4>Output bias</h4>';addControl(bias,'Flap bias',()=>brain.b,v=>brain.b=v);root.append(bias);}
function sigmoid(x){return 1/(1+Math.exp(-Math.max(-20,Math.min(20,x))));}
function think(){const next=botPipes.find(p=>p.x+58>bot.x) || {x:botCanvas.width,top:105,bottom:255};const inputs=[bot.y/346,Math.max(-1,Math.min(1,bot.velocity/10)),Math.max(0,Math.min(1,(next.x-bot.x)/botCanvas.width)),next.top/346,next.bottom/346];return {inputs,output:sigmoid(brain.b+inputs.reduce((sum,input,i)=>sum+input*brain.w[i],0))};}
function resetBot(){bot={x:110,y:190,r:14,velocity:0};botPipes=[];botFrame=0;botScore=0;botScoreEl.textContent='0';}
function addBotPipe(){const top=55+Math.random()*145;botPipes.push({x:botCanvas.width+30,top,bottom:top+132,passed:false});}
function drawBotPipe(p){botCtx.fillStyle='#63b945';botCtx.strokeStyle='#245e39';botCtx.lineWidth=3;botCtx.fillRect(p.x,0,58,p.top);botCtx.strokeRect(p.x,0,58,p.top);botCtx.fillRect(p.x-5,p.top-18,68,18);botCtx.strokeRect(p.x-5,p.top-18,68,18);botCtx.fillRect(p.x,p.bottom,58,346-p.bottom);botCtx.strokeRect(p.x,p.bottom,58,346-p.bottom);botCtx.fillRect(p.x-5,p.bottom,68,18);botCtx.strokeRect(p.x-5,p.bottom,68,18);}
function drawBot(){botCtx.save();botCtx.translate(bot.x,bot.y);botCtx.rotate(Math.max(-.4,Math.min(.7,bot.velocity*.07)));botCtx.fillStyle='#ffd842';botCtx.strokeStyle='#17354a';botCtx.lineWidth=3;botCtx.beginPath();botCtx.arc(0,0,bot.r,0,Math.PI*2);botCtx.fill();botCtx.stroke();botCtx.fillStyle='#fff';botCtx.beginPath();botCtx.arc(6,-6,5,0,Math.PI*2);botCtx.fill();botCtx.stroke();botCtx.fillStyle='#17354a';botCtx.beginPath();botCtx.arc(8,-6,2,0,Math.PI*2);botCtx.fill();botCtx.fillStyle='#ef7544';botCtx.beginPath();botCtx.moveTo(12,1);botCtx.lineTo(25,6);botCtx.lineTo(12,10);botCtx.closePath();botCtx.fill();botCtx.stroke();botCtx.restore();}
function stopBot(){botRunning=false;if(botScore>botBest){botBest=botScore;localStorage.setItem('manualBirdBest',botBest);botBestEl.textContent=botBest;}}
function botLoop(){botCtx.fillStyle='#80d8ef';botCtx.fillRect(0,0,500,390);drawCloudBot(70,80,.7);drawCloudBot(355,128,.5);botCtx.fillStyle='#87cf5c';botCtx.fillRect(0,346,500,44);botCtx.fillStyle='#d6a85d';botCtx.fillRect(0,364,500,26);if(botFrame%102===0)addBotPipe();botPipes.forEach(p=>{p.x-=2.45;drawBotPipe(p);});botPipes=botPipes.filter(p=>p.x>-75);const decision=think(),output=decision.output,flap=output>.5;drawActivations(decision);botOutputEl.textContent=output.toFixed(2);botActionEl.textContent=flap?'FLAP!':'WAIT';botActionEl.classList.toggle('flapping',flap);if(flap)bot.velocity=-5.6;bot.velocity+=.38;bot.y+=bot.velocity;drawBot();for(const p of botPipes){if(!p.passed&&p.x+58<bot.x){p.passed=true;botScore++;botScoreEl.textContent=botScore;}if(bot.x+bot.r>p.x&&bot.x-bot.r<p.x+58&&(bot.y-bot.r<p.top||bot.y+bot.r>p.bottom)){stopBot();return;}}if(bot.y+bot.r>=346||bot.y-bot.r<0){stopBot();return;}botFrame++;botAnimation=requestAnimationFrame(botLoop);}
function drawCloudBot(x,y,s){botCtx.fillStyle='rgba(255,255,255,.75)';botCtx.beginPath();botCtx.arc(x,y,15*s,0,Math.PI*2);botCtx.arc(x+20*s,y-8*s,20*s,0,Math.PI*2);botCtx.arc(x+43*s,y,14*s,0,Math.PI*2);botCtx.fill();}
function drawActivations(d){const c=document.querySelector('#activation-graph'),x=c.getContext('2d'),inputX=52,outputX=240,ys=[70,120,170,220,270],labels=['HEIGHT','SPEED','DIST','TOP','BOTTOM'];x.clearRect(0,0,300,390);x.fillStyle='#eefaff';x.fillRect(0,0,300,390);x.font='800 11px Nunito';x.fillStyle='#406273';x.textAlign='center';x.fillText('FIVE INPUTS',inputX,28);x.fillText('OUTPUT',outputX,28);for(let i=0;i<5;i++){const w=brain.w[i];x.strokeStyle=w>=0?'#3b9db9':'#e96874';x.globalAlpha=.12+Math.min(.7,Math.abs(w)/6*.7);x.lineWidth=1+Math.abs(w)*.7;x.beginPath();x.moveTo(inputX+17,ys[i]);x.lineTo(outputX-20,170);x.stroke();}x.globalAlpha=1;const node=(px,py,value,fill,label)=>{x.fillStyle=fill;x.globalAlpha=.25+.75*Math.min(1,Math.abs(value));x.beginPath();x.arc(px,py,17,0,Math.PI*2);x.fill();x.globalAlpha=1;x.strokeStyle='#17354a';x.lineWidth=2;x.stroke();x.fillStyle='#17354a';x.font='800 10px Nunito';x.fillText(value.toFixed(2),px,py+4);x.fillStyle='#406273';x.font='800 9px Nunito';x.fillText(label,px,py+31);};d.inputs.forEach((v,i)=>node(inputX,ys[i],v,v<0?'#e96874':'#63b9d9',labels[i]));node(outputX,170,d.output,'#ef7544',d.output>.5?'FLAP':'WAIT');x.fillStyle='#406273';x.font='700 10px Nunito';x.fillText('line thickness = weight strength',150,350);}
function startBot(){cancelAnimationFrame(botAnimation);resetBot();botRunning=true;botLoop();}
document.querySelector('#bot-start').addEventListener('click',startBot);document.querySelector('#starter-preset').addEventListener('click',()=>{brain=starter();renderControls();drawActivations(think());});document.querySelector('#random-brain').addEventListener('click',()=>{brain=randomBrain();renderControls();drawActivations(think());});renderControls();resetBot();botCtx.fillStyle='#80d8ef';botCtx.fillRect(0,0,500,390);drawCloudBot(70,80,.7);botCtx.fillStyle='#87cf5c';botCtx.fillRect(0,346,500,44);drawBot();drawActivations(think());
}

// Evolution arena: 63 birds, six inputs (including obstacle speed), five courses, then top three survive.
if (document.querySelector('#evolution-game')) {
const evoCanvas=document.querySelector('#evolution-game'),evoCtx=evoCanvas.getContext('2d');
const evoEl={gen:document.querySelector('#evo-generation'),round:document.querySelector('#evo-round'),alive:document.querySelector('#evo-alive'),leader:document.querySelector('#evo-leader'),leaderScore:document.querySelector('#evo-leader-score'),roundHigh:document.querySelector('#evo-round-high'),allHigh:document.querySelector('#evo-all-high'),difficulty:document.querySelector('#difficulty-fill'),difficultyText:document.querySelector('#difficulty-text'),history:document.querySelector('#round-history'),status:document.querySelector('#evo-status')};
let population=[],evoPipes=[],evoGeneration=1,evoRound=1,evoFrame=0,evoRunning=false,evoPaused=false,evoAnimation,evoSeed=1,evoAllHigh=0,evoSpeed=1,evoDifficultyRate=1,evoMutation=0.25,evoCarry=0;
const rand=()=>{evoSeed=(evoSeed*1664525+1013904223)>>>0;return evoSeed/4294967296;};
function randomGenome(){const r=()=>rand()*2-1;return {w1:Array.from({length:6},()=>Array.from({length:4},r)),b1:Array.from({length:4},r),w2:Array.from({length:4},()=>Array.from({length:4},r)),b2:Array.from({length:4},r),w3:Array.from({length:4},r),b3:r()};}
function copyGenome(g){return {w1:g.w1.map(row=>[...row]),b1:[...g.b1],w2:g.w2.map(row=>[...row]),b2:[...g.b2],w3:[...g.w3],b3:g.b3};}
function mutate(g){const child=copyGenome(g),chance=.02+evoMutation*.14,amount=.05+evoMutation*.45,change=v=>Math.max(-6,Math.min(6,v+(rand()<chance?(rand()*2-1)*amount:0)));child.w1=child.w1.map(row=>row.map(change));child.b1=child.b1.map(change);child.w2=child.w2.map(row=>row.map(change));child.b2=child.b2.map(change);child.w3=child.w3.map(change);child.b3=change(child.b3);return child;}
function forward(g,inputs){const h1=g.b1.map((b,j)=>Math.tanh(b+inputs.reduce((s,v,i)=>s+v*g.w1[i][j],0)));const h2=g.b2.map((b,j)=>Math.tanh(b+h1.reduce((s,v,i)=>s+v*g.w2[i][j],0)));return sigmoid(g.b3+h2.reduce((s,v,i)=>s+v*g.w3[i],0));}
function makePopulation(genomes){return genomes.map((genome,id)=>({id,genome,total:0,roundScore:0,alive:true,x:118,y:205,v:0,passed:0,deathFrame:0}));}
function freshFlock(){evoSeed=(Date.now()>>>0);population=makePopulation(Array.from({length:63},randomGenome));evoGeneration=1;evoRound=1;evoAllHigh=0;clearHistory();startEvoRound();evoRunning=false;evoPaused=false;drawEvolution();updateEvoUI();evoEl.status.textContent='Fresh flock created. Generations 1–5 use fixed courses for fair comparison.';}
function clearHistory(){[...evoEl.history.children].forEach((row,i)=>{row.className='';row.innerHTML=`Round ${i+1} <span>not started</span>`;});}
function startEvoRound(){evoPipes=[];evoFrame=0;evoCarry=0;evoSeed=(evoGeneration<=5?evoRound*911+17:Date.now()+evoGeneration*10000+evoRound*911)>>>0;population.forEach(b=>Object.assign(b,{alive:true,x:118,y:205,v:0,passed:0,roundScore:0,deathFrame:0}));updateEvoUI();}
function spawnEvoPipe(){const hard=Math.min(.82,evoFrame/(3000/evoDifficultyRate));const gap=150-hard*58;const top=48+rand()*(270-gap);evoPipes.push({x:evoCanvas.width+35,top,bottom:top+gap});}
function updateEvoUI(){const alive=population.filter(b=>b.alive).length,leader=[...population].sort((a,b)=>(b.alive?b.passed*10000+evoFrame:b.roundScore)-(a.alive?a.passed*10000+evoFrame:a.roundScore))[0];evoEl.gen.textContent=evoGeneration;evoEl.round.textContent=`${evoRound} / 5`;evoEl.alive.textContent=alive;evoEl.leader.textContent=leader?`Bird #${leader.id+1}`:'—';evoEl.leaderScore.textContent=leader?`${leader.passed} pipes this race · ${leader.total.toFixed(0)} total fitness`:'waiting to race';const high=Math.max(0,...population.map(b=>b.passed));evoEl.roundHigh.textContent=high;evoEl.allHigh.textContent=evoAllHigh;const hard=Math.min(82,Math.round(evoFrame/(3000/evoDifficultyRate)*82));evoEl.difficulty.style.width=`${Math.max(8,hard)}%`;evoEl.difficultyText.textContent=hard<25?'Easy · wide gaps':hard<55?'Faster · smaller gaps · stronger gravity':'Hard · tight gaps · rapid pipes';}
function finishEvoRound(){evoRunning=false;population.forEach(b=>{b.roundScore=b.passed*10000+(b.deathFrame||evoFrame);b.total+=b.roundScore;});const winner=[...population].sort((a,b)=>b.roundScore-a.roundScore)[0],high=winner.passed;evoAllHigh=Math.max(evoAllHigh,high);const row=evoEl.history.children[evoRound-1];row.className='done';row.innerHTML=`Round ${evoRound} <span>Bird #${winner.id+1} · ${high} pipes</span>`;if(evoRound<5){evoRound++;evoEl.status.textContent=`Round complete. Preparing random course ${evoRound} of 5…`;setTimeout(()=>{startEvoRound();evoRunning=true;tickEvolution();},650);}else{selectParents();}updateEvoUI();}
function selectParents(){const winners=[...population].sort((a,b)=>b.total-a.total).slice(0,3);const names=winners.map(b=>`#${b.id+1}`).join(', ');const next=[];winners.forEach(winner=>{next.push(copyGenome(winner.genome));for(let i=0;i<20;i++)next.push(mutate(winner.genome));});population=makePopulation(next);evoGeneration++;evoRound=1;clearHistory();const courseNote=evoGeneration<=5?'Fixed courses remain active for fair comparison.':'Random courses are now active: robustness matters.';evoEl.status.textContent=`Generation ${evoGeneration}: winners ${names} survived. ${courseNote}`;startEvoRound();evoRunning=true;tickEvolution();}
function drawEvoPipe(p){evoCtx.fillStyle='#63b945';evoCtx.strokeStyle='#245e39';evoCtx.lineWidth=3;evoCtx.fillRect(p.x,0,58,p.top);evoCtx.strokeRect(p.x,0,58,p.top);evoCtx.fillRect(p.x-5,p.top-18,68,18);evoCtx.strokeRect(p.x-5,p.top-18,68,18);evoCtx.fillRect(p.x,p.bottom,58,372-p.bottom);evoCtx.strokeRect(p.x,p.bottom,58,372-p.bottom);evoCtx.fillRect(p.x-5,p.bottom,68,18);evoCtx.strokeRect(p.x-5,p.bottom,68,18);}
function drawEvolution(){evoCtx.fillStyle='#80d8ef';evoCtx.fillRect(0,0,660,420);drawEvoCloud(85,88,.9);drawEvoCloud(450,145,.6);evoPipes.forEach(drawEvoPipe);evoCtx.fillStyle='#80c850';evoCtx.fillRect(0,372,660,48);evoCtx.fillStyle='#d6a85d';evoCtx.fillRect(0,394,660,26);const leader=[...population].sort((a,b)=>b.passed-a.passed||a.id-b.id)[0];population.filter(b=>b.alive).forEach(b=>{evoCtx.fillStyle=b===leader?'#ffd949':'#ef7544';evoCtx.globalAlpha=b===leader?1:.55;evoCtx.beginPath();evoCtx.arc(b.x+(b.id%7-3)*2,b.y+(b.id%5-2)*2,5,0,Math.PI*2);evoCtx.fill();});evoCtx.globalAlpha=1;if(leader&&leader.alive){evoCtx.fillStyle='#17354a';evoCtx.font='800 11px Nunito';evoCtx.fillText('LEADER',leader.x-23,leader.y-13);}}
function drawEvoCloud(x,y,s){evoCtx.fillStyle='rgba(255,255,255,.72)';evoCtx.beginPath();evoCtx.arc(x,y,15*s,0,Math.PI*2);evoCtx.arc(x+20*s,y-8*s,20*s,0,Math.PI*2);evoCtx.arc(x+43*s,y,14*s,0,Math.PI*2);evoCtx.fill();}
function stepEvolution(){const hard=Math.min(.82,evoFrame/(3000/evoDifficultyRate)),speed=2.35+hard*1.65,interval=Math.max(72,100-Math.floor(hard*28));if(evoFrame%interval===0)spawnEvoPipe();evoPipes.forEach(p=>p.x-=speed);evoPipes=evoPipes.filter(p=>p.x>-80);for(const b of population){if(!b.alive)continue;const next=evoPipes.find(p=>p.x+58>b.x)||{x:660,top:110,bottom:260};const inputs=[b.y/372,Math.max(-1,Math.min(1,b.v/10)),Math.max(0,Math.min(1,(next.x-b.x)/660)),next.top/372,next.bottom/372,speed/4];if(forward(b.genome,inputs)>.5)b.v=-5.8;b.v+=.36+hard*.07;b.y+=b.v;for(const p of evoPipes){if(p.x+58<b.x&&p.x+58>=b.x-speed)b.passed++;if(b.x+5>p.x&&b.x-5<p.x+58&&(b.y-5<p.top||b.y+5>p.bottom)){b.alive=false;b.deathFrame=evoFrame;}}if((b.y<5||b.y>367)&&b.alive){b.alive=false;b.deathFrame=evoFrame;}}evoFrame++;if(!population.some(b=>b.alive)||evoFrame>3100){finishEvoRound();return false;}return true;}
function tickEvolution(){if(!evoRunning||evoPaused)return;evoCarry+=evoSpeed;let steps=Math.floor(evoCarry);evoCarry-=steps;while(steps-->0&&evoRunning){if(!stepEvolution())return;}drawEvolution();updateEvoUI();evoAnimation=requestAnimationFrame(tickEvolution);}
function beginEvolution(){if(!population.length)freshFlock();if(evoPaused){evoPaused=false;evoRunning=true;document.querySelector('#evo-pause').textContent='Pause';tickEvolution();return;}if(!evoRunning){startEvoRound();evoRunning=true;tickEvolution();}evoEl.status.textContent='Five courses are racing. Fitness combines pipes passed and survival time.';}
document.querySelector('#evo-start').addEventListener('click',beginEvolution);document.querySelector('#evo-pause').addEventListener('click',()=>{if(!evoRunning)return;evoPaused=!evoPaused;document.querySelector('#evo-pause').textContent=evoPaused?'Resume':'Pause';if(!evoPaused)tickEvolution();});document.querySelector('#evo-reset').addEventListener('click',()=>{cancelAnimationFrame(evoAnimation);freshFlock();});const speedKnob=document.querySelector('#simulation-speed'),speedValue=document.querySelector('#simulation-speed-value'),difficultyKnob=document.querySelector('#difficulty-rate'),difficultyValue=document.querySelector('#difficulty-rate-value'),mutationKnob=document.querySelector('#mutation-strength'),mutationValue=document.querySelector('#mutation-strength-value');speedKnob.addEventListener('input',()=>{evoSpeed=Number(speedKnob.value);speedValue.textContent=`${evoSpeed}×`;});difficultyKnob.addEventListener('input',()=>{evoDifficultyRate=Number(difficultyKnob.value);difficultyValue.textContent=`${evoDifficultyRate}×`;updateEvoUI();});mutationKnob.addEventListener('input',()=>{evoMutation=Number(mutationKnob.value);mutationValue.textContent=evoMutation<=.3?'gentle':evoMutation<=.65?'medium':'wild';});freshFlock();
}
